<?php
/** @var $block \Profair\ProductBooking\Block\Product\BookProduct */
$product = $block->getProduct();
?>
<div class="rFormWrap">
    <div class="minform_order">
        <div class="wrapfield">
            <form class="profair-book-product"
                  novalidate
                  action="<?= $block->escapeUrl($block->getActionUrl()) ?>"
                  method="post"
                  data-mage-init='{"validation": {"errorClass": "fielderror"}}'
                  id="profair-book-product">
            <div class="field">
                <label for="mobile_phone"></label>
                <input id="mobile_phone" autocomplete="off" class="f122phone" type="text"
                       name="mobile_phone" placeholder="<?= __('Mobile phone') ?>*" data-validate="{required:true}">
                <input id="product_sku" name="product_sku" type="hidden" value="<?= $product->getSku() ?>"/>
                <div class="button">
                    <button class="action primary to-order"
                            title="<?= $block->escapeHtmlAttr(__('Book product by special price')) ?>"
                            type="submit"><?= $block->escapeHtml(__('Book product by special price')) ?></button>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    ".to-order": {
        "book-product": {
            "formContainer": "#profair-book-product",
            "mobilePhoneElement": "#mobile_phone",
            "productSku": "<?= $product->getSku() ?>"
        }
    }
}
</script>