<div class="wrap980">
<div class="shareposition">
    <div class="leftShare">
        <div class="wraptext"><?= $block->getChildHtml('profair.sale.promotion.banner') ?></div>
        <div class="clear">&nbsp;</div>
        <div class="timerWrap"><?= $block->getChildHtml('profair.sale.promotion.timer') ?></div>
    </div>
    <div class="rightShare">
        <?= $block->getChildHtml('profair.sale.send_request') ?>
    </div>
</div>
