<?php /** @var \Profair\RequestPopup\Block\Request\Popup $block */ ?>
<form class="profair-contact-request"
      novalidate
      action="<?= $block->escapeUrl($block->getActionUrl()) ?>"
      method="post"
      data-mage-init='{"validation": {"errorClass": "mage-error"}}'
      id="contact-validate-detail">
    <div class="formShare">
        <h4>Zostaw prośbę</h4>
        <p>o bezpłatną konsultację, a nasz specjalista skontaktuje się z Tobą</p>
        <div class="wrapfield">
            <div class="field">
                <label class="label" for="f1name"></label>
                <input id="f1name" class="mlfinp" name="name" type="text" value="" placeholder="Ваше имя*" />
            </div>
            <div class="field">
                <label class="label" for="f1phone"></label>
                <input id="f1phone" class="mlfinp" name="phone" type="text" value="" placeholder="Моб. телефон*">
            </div>
            <div class="field">
                <label class="label" for="f1email"></label>
                <input id="f1email" class="mlfinp" name="email" type="text" value="" placeholder="Ваш Email">
            </div>
            <div class="button">
                <button class="action primary" title="<?= $block->escapeHtmlAttr(__('Send')) ?>"
                        type="submit"><?= $block->escapeHtml(__('Send')) ?></button>
            </div>
        </div>
    </div>
</form>