<p><input id="sharecount" name="sharecount" type="hidden" value="12.09.2022 02:09:12, 2022.12.09 00"></p>
<div class="timerWrap">
    <div class="deadlineTitle">До конца акции:</div>
    <div id="mlfcounter" class="countdownHolder"><span class="countDays"> <span
                class="countDiv countDiv0">дней</span></span><span class="countHours"> <span
                class="countDiv countDiv1">часов</span></span><span class="countMinutes"> <span
                class="countDiv countDiv2">минут</span></span><span class="countSeconds"> <span
                class="countDiv countDiv3">секунд</span></span></div>
</div>