<?php /* @var \Profair\RequestPopup\Block\Timer $block*/ ?>
<?php if($block->isCountdownEnabled()): ?>
    <div class="deadlineTitle"><?= __('До конца акции:') ?></div>
    <div id="mlfcounter" class="countdownHolder"></div>
<?php endif; ?>
<script type="text/x-magento-init">
{
    ".countdownHolder": {
        "countdown": {
            "startDate": "<?php echo date('Y/m/d H:i:s'); ?>",
            "dateAndTime": "<?php echo $block->getCountdownEndDate(); ?>"
        }
    }
}
</script>